// <auto-generated />
using System;
using ChatrBox.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChatrBox.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231130223428_initialMigrationNumber3")]
    partial class initialMigrationNumber3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ChatrBox.Data.Community", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ContentFilter")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Visibility")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Communities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContentFilter = 0,
                            Description = "System generated community used for testing layouts",
                            ImageHash = "",
                            ImageUrl = "",
                            Name = "Loreum Ipsum",
                            OwnerId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Visibility = 0
                        });
                });

            modelBuilder.Entity("ChatrBox.Data.CommunityUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("CanPost")
                        .HasColumnType("bit");

                    b.Property<bool>("CanRead")
                        .HasColumnType("bit");

                    b.Property<string>("ChatrId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CommunityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChatrId");

                    b.HasIndex("CommunityId");

                    b.ToTable("CommunityUsers");
                });

            modelBuilder.Entity("ChatrBox.Data.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<string>("MessagePlain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("TopicId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsEdited = false,
                            MessagePlain = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vel semper risus. Aenean vel malesuada dui, semper rutrum tortor. Nulla ex mi, aliquet nec aliquet vitae, interdum vitae lorem. Nulla semper varius sem. Maecenas placerat erat mattis, tempor orci vitae, tincidunt nisl. Donec justo sem, fringilla quis bibendum nec, commodo quis nisl. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi molestie vitae neque ut bibendum.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsEdited = false,
                            MessagePlain = "Curabitur eu condimentum eros. Cras vel sodales sapien, vitae rutrum dui. Donec eros erat, cursus vel congue sed, venenatis sit amet augue. Curabitur eget mollis diam, non scelerisque velit. Sed tincidunt risus vitae erat tempus consequat. Fusce nulla velit, cursus sed efficitur sed, sagittis id leo. Etiam volutpat urna purus, id scelerisque lacus gravida ut. Integer neque nunc, placerat sit amet tincidunt ut, scelerisque a velit. Aliquam id leo commodo, vehicula felis in, posuere mi. Fusce ut magna eu dui laoreet blandit quis quis ipsum.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsEdited = false,
                            MessagePlain = "Quisque porta sapien et augue semper, non sollicitudin mauris lacinia. Nunc rutrum nunc bibendum dolor posuere scelerisque. Nam consectetur lectus id rutrum aliquam. Aenean id tincidunt arcu. Aliquam ut pretium odio. Proin fringilla a nisl sed ultrices. Proin mauris est, pellentesque eget sodales id, cursus sed sapien. Phasellus tempor pretium erat, sit amet porta est viverra nec.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsEdited = false,
                            MessagePlain = "Maecenas in mi nec lectus condimentum dapibus quis porta ante. Aliquam a scelerisque enim, vitae sodales risus. Aliquam interdum, ante nec aliquam aliquam, enim orci rutrum velit, at tincidunt elit nisl ut diam. Maecenas at nisl lorem. In volutpat lorem ut ex molestie, id hendrerit quam facilisis. Nulla faucibus lectus at eleifend congue. Praesent nulla massa, bibendum id elit vitae, ultricies tempor felis. Sed mattis, massa vel pulvinar ultricies, dolor ex dapibus risus, sit amet dictum dolor enim ac quam.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 5,
                            IsEdited = false,
                            MessagePlain = "Suspendisse eu ligula eget libero bibendum sodales sit amet quis lorem. Nunc maximus maximus imperdiet. Nunc dapibus nibh quam, vel bibendum lectus venenatis imperdiet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris ipsum ante, mollis vel blandit et, fermentum vitae lacus. Cras sagittis quam vel fermentum fringilla. Praesent fermentum viverra elit. Donec consectetur orci in lorem ultricies laoreet. Curabitur imperdiet rutrum elit vel venenatis. Nulla vel velit in justo scelerisque eleifend. Phasellus sodales commodo lobortis. Nulla rutrum nunc nisi. Vestibulum gravida condimentum sagittis. Sed ut lacus non libero mollis suscipit eu in erat. Praesent eu iaculis ante, sed rutrum nulla. Maecenas nec est rutrum, ornare sem et, mollis ipsum.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 6,
                            IsEdited = false,
                            MessagePlain = "Phasellus id odio volutpat, condimentum nisi vitae, dapibus mauris. Ut sed mi orci. Maecenas mi nunc, blandit nec hendrerit ac, maximus quis turpis. Nulla ex mi, consequat non orci posuere, tincidunt convallis nibh. Phasellus purus purus, porta quis lobortis at, lobortis sit amet lacus. Fusce sem libero, ullamcorper ut cursus quis, cursus id neque. Integer porttitor libero sit amet pellentesque porttitor. Nunc lacus enim, dapibus in scelerisque in, accumsan id felis. Donec posuere, dolor a tincidunt maximus, justo nisl imperdiet massa, vitae pharetra nunc erat non leo.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 7,
                            IsEdited = false,
                            MessagePlain = "Nunc et turpis et enim mollis volutpat consectetur eget mi. Cras ante erat, vehicula ac arcu quis, iaculis euismod est. Donec fringilla, urna sodales sodales vehicula, ligula mi finibus urna, nec euismod risus quam vel ex. Vestibulum auctor lorem consectetur nisl faucibus facilisis. In maximus sollicitudin justo id hendrerit. Integer sodales mollis quam, id ultricies tellus. Aliquam a purus nulla.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 8,
                            IsEdited = false,
                            MessagePlain = "Etiam suscipit volutpat sapien, ac rhoncus justo mollis in. Sed volutpat vulputate eleifend. Duis lacinia dui viverra metus sollicitudin, et fermentum velit venenatis. Praesent lorem urna, placerat et tortor vitae, sagittis fermentum risus. Vestibulum non est vitae nibh hendrerit dignissim a sollicitudin dolor. Donec ac mollis elit. Pellentesque commodo, turpis nec consequat tempor, tortor massa tempor eros, sit amet volutpat purus tellus fringilla elit. Maecenas tincidunt aliquam ante. Suspendisse potenti. Morbi non mi aliquet augue feugiat congue sed tincidunt tellus. Vestibulum mollis, sapien vitae placerat luctus, sapien odio porttitor orci, ut porta nibh ex non velit. Donec iaculis eros in urna vulputate, in consectetur lacus sagittis. Nullam ac semper dolor. Aenean eu tellus in purus semper volutpat sit amet et odio.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 9,
                            IsEdited = false,
                            MessagePlain = "Aenean lacinia risus non erat varius laoreet. Nullam maximus sollicitudin maximus. Mauris euismod efficitur tempor. Aenean lacinia quam sed enim ullamcorper tempor. Donec et rutrum est, quis aliquam magna. Vestibulum cursus tincidunt augue, nec consequat sapien ultricies non. Donec scelerisque dictum turpis sit amet sagittis. Duis sodales mauris nec diam hendrerit hendrerit. Nullam scelerisque ligula in faucibus faucibus. Vestibulum maximus magna at nisl scelerisque congue. Fusce blandit varius eros, vitae placerat ex egestas et. Quisque viverra libero sed arcu scelerisque, elementum volutpat purus ultricies. Mauris in turpis ut magna convallis gravida. Donec ornare faucibus dui sed varius. Sed pulvinar urna vel sapien euismod pellentesque.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 10,
                            IsEdited = false,
                            MessagePlain = "Etiam nec enim sem. Vivamus sed nunc congue, lacinia risus a, porttitor est. Curabitur mauris libero, vulputate eget lobortis sed, dignissim quis libero. Curabitur eget ipsum feugiat, condimentum justo sed, porttitor magna. Vestibulum rhoncus eros mauris. Aenean ultrices urna in massa fringilla, sed finibus justo rhoncus. Proin interdum non risus nec facilisis.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 11,
                            IsEdited = false,
                            MessagePlain = "Vestibulum ullamcorper porttitor eleifend. Etiam vehicula justo in est facilisis, nec lobortis dolor egestas. Proin lectus sapien, lacinia semper leo ac, imperdiet vehicula enim. Morbi sodales placerat ipsum et efficitur. Praesent ligula mi, ornare vel sagittis non, posuere non dui. Nunc interdum placerat mauris, ut elementum mauris aliquam in. Nulla egestas, tellus vel iaculis ullamcorper, nunc justo aliquam quam, et cursus felis mi non nulla. Sed ac auctor risus, ut aliquam turpis. Pellentesque vel tristique est, maximus iaculis sem. Phasellus turpis felis, euismod a elementum non, tincidunt id mauris. Praesent mattis tempor dui, et rutrum justo bibendum vel.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 12,
                            IsEdited = false,
                            MessagePlain = "In viverra purus pretium, viverra justo non, commodo lacus. Suspendisse quis lorem risus. Vestibulum sagittis eros odio, non egestas quam scelerisque vitae. Suspendisse sed eros eros. Sed imperdiet scelerisque mollis. Pellentesque faucibus rhoncus est. Sed lacinia odio elit. Maecenas fringilla nulla nec turpis congue, et luctus est ultrices. Aliquam porttitor massa volutpat purus tincidunt pharetra. Pellentesque placerat ultrices turpis eget porta. Duis posuere nisi vel arcu ultricies, ut hendrerit sapien ultrices. Curabitur tristique odio quis ex placerat mollis. Aliquam porttitor eros quis tempus varius. Pellentesque ultricies nunc vestibulum elit sodales fermentum. Praesent molestie sit amet tellus id commodo. Interdum et malesuada fames ac ante ipsum primis in faucibus.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 13,
                            IsEdited = false,
                            MessagePlain = "Nunc et turpis et enim mollis volutpat consectetur eget mi. Cras ante erat, vehicula ac arcu quis, iaculis euismod est. Donec fringilla, urna sodales sodales vehicula, ligula mi finibus urna, nec euismod risus quam vel ex. Vestibulum auctor lorem consectetur nisl faucibus facilisis. In maximus sollicitudin justo id hendrerit. Integer sodales mollis quam, id ultricies tellus. Aliquam a purus nulla.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 14,
                            IsEdited = false,
                            MessagePlain = "Vivamus varius nec urna quis scelerisque. Curabitur pretium felis turpis, in dignissim sapien faucibus eget. Nulla dictum nec nisi eu lacinia. Proin ut ante vel erat consectetur laoreet at ut dui. Nam eu bibendum nunc. Cras a lorem sit amet quam mollis fermentum id tempor sapien. Curabitur quis eleifend dui. Vestibulum euismod, augue id auctor pretium, velit ligula aliquam odio, eget dictum leo mi ut tortor.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 15,
                            IsEdited = false,
                            MessagePlain = "Etiam non leo non neque tincidunt lobortis. Proin interdum, odio bibendum porta posuere, lacus lectus placerat mi, sed accumsan velit metus in massa. Sed fermentum vel mauris rhoncus cursus. Donec fermentum pharetra lorem sed eleifend. Aenean non lacinia diam. Mauris nec malesuada massa, eu rutrum quam. Quisque tempus eleifend sem, non tempor purus ultricies eget.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 16,
                            IsEdited = false,
                            MessagePlain = "Etiam nec enim sem. Vivamus sed nunc congue, lacinia risus a, porttitor est. Curabitur mauris libero, vulputate eget lobortis sed, dignissim quis libero. Curabitur eget ipsum feugiat, condimentum justo sed, porttitor magna. Vestibulum rhoncus eros mauris. Aenean ultrices urna in massa fringilla, sed finibus justo rhoncus. Proin interdum non risus nec facilisis.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 17,
                            IsEdited = false,
                            MessagePlain = "Suspendisse quis tristique augue, quis aliquet magna. Maecenas in libero nisi. Duis scelerisque ex sit amet consectetur accumsan. Phasellus elit sapien, mattis vel gravida nec, condimentum nec quam. Nam sodales interdum enim quis luctus. Duis ornare eleifend pulvinar. Morbi commodo tincidunt dolor, a finibus sem. Pellentesque id scelerisque diam.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 18,
                            IsEdited = false,
                            MessagePlain = "Nunc lacus ligula, dapibus id venenatis a, vestibulum id sem. Curabitur sed neque metus. Aliquam erat volutpat. Aenean placerat iaculis lacus, nec tincidunt libero finibus eu. Duis varius, est eget ullamcorper aliquam, diam diam egestas nibh, eu maximus ligula eros eu risus. In dui sem, lacinia in dui non, pretium tempus neque. Nullam in aliquet libero. Curabitur pulvinar orci lorem, at venenatis lorem convallis et. Sed placerat ac ante in accumsan. Sed venenatis, nisi eget viverra fermentum, erat justo feugiat mi, at dignissim odio mauris commodo eros. Integer quis orci a enim tempor gravida id nec libero. Sed volutpat tortor nisi, aliquam pharetra ex interdum at. Donec pharetra consequat facilisis. Aenean a mattis leo. Etiam tincidunt nisi efficitur dui ornare, eu pretium massa sagittis. Aliquam finibus mauris nec massa pellentesque, eget cursus elit condimentum.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 19,
                            IsEdited = false,
                            MessagePlain = "Aenean lacinia risus non erat varius laoreet. Nullam maximus sollicitudin maximus. Mauris euismod efficitur tempor. Aenean lacinia quam sed enim ullamcorper tempor. Donec et rutrum est, quis aliquam magna. Vestibulum cursus tincidunt augue, nec consequat sapien ultricies non. Donec scelerisque dictum turpis sit amet sagittis. Duis sodales mauris nec diam hendrerit hendrerit. Nullam scelerisque ligula in faucibus faucibus. Vestibulum maximus magna at nisl scelerisque congue. Fusce blandit varius eros, vitae placerat ex egestas et. Quisque viverra libero sed arcu scelerisque, elementum volutpat purus ultricies. Mauris in turpis ut magna convallis gravida. Donec ornare faucibus dui sed varius. Sed pulvinar urna vel sapien euismod pellentesque.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 20,
                            IsEdited = false,
                            MessagePlain = "Nunc et turpis et enim mollis volutpat consectetur eget mi. Cras ante erat, vehicula ac arcu quis, iaculis euismod est. Donec fringilla, urna sodales sodales vehicula, ligula mi finibus urna, nec euismod risus quam vel ex. Vestibulum auctor lorem consectetur nisl faucibus facilisis. In maximus sollicitudin justo id hendrerit. Integer sodales mollis quam, id ultricies tellus. Aliquam a purus nulla.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 21,
                            IsEdited = false,
                            MessagePlain = "Vivamus varius nec urna quis scelerisque. Curabitur pretium felis turpis, in dignissim sapien faucibus eget. Nulla dictum nec nisi eu lacinia. Proin ut ante vel erat consectetur laoreet at ut dui. Nam eu bibendum nunc. Cras a lorem sit amet quam mollis fermentum id tempor sapien. Curabitur quis eleifend dui. Vestibulum euismod, augue id auctor pretium, velit ligula aliquam odio, eget dictum leo mi ut tortor.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 22,
                            IsEdited = false,
                            MessagePlain = "Nunc et turpis et enim mollis volutpat consectetur eget mi. Cras ante erat, vehicula ac arcu quis, iaculis euismod est. Donec fringilla, urna sodales sodales vehicula, ligula mi finibus urna, nec euismod risus quam vel ex. Vestibulum auctor lorem consectetur nisl faucibus facilisis. In maximus sollicitudin justo id hendrerit. Integer sodales mollis quam, id ultricies tellus. Aliquam a purus nulla.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 23,
                            IsEdited = false,
                            MessagePlain = "Aenean lacinia risus non erat varius laoreet. Nullam maximus sollicitudin maximus. Mauris euismod efficitur tempor. Aenean lacinia quam sed enim ullamcorper tempor. Donec et rutrum est, quis aliquam magna. Vestibulum cursus tincidunt augue, nec consequat sapien ultricies non. Donec scelerisque dictum turpis sit amet sagittis. Duis sodales mauris nec diam hendrerit hendrerit. Nullam scelerisque ligula in faucibus faucibus. Vestibulum maximus magna at nisl scelerisque congue. Fusce blandit varius eros, vitae placerat ex egestas et. Quisque viverra libero sed arcu scelerisque, elementum volutpat purus ultricies. Mauris in turpis ut magna convallis gravida. Donec ornare faucibus dui sed varius. Sed pulvinar urna vel sapien euismod pellentesque.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 24,
                            IsEdited = false,
                            MessagePlain = "Pellentesque lacinia ligula at massa vulputate finibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et pretium dui. Vestibulum porta urna vitae lacus egestas, ac venenatis nulla facilisis. Aenean accumsan nibh sit amet velit condimentum vulputate. Nulla sed mollis purus. Mauris egestas consequat lacus vel commodo. Nulla eget neque est. Duis at commodo ipsum. Nam et turpis imperdiet, aliquet nibh nec, tristique sapien. Sed ultricies nulla erat, luctus auctor turpis lobortis nec. Fusce vitae molestie tortor. Duis dictum faucibus efficitur.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 25,
                            IsEdited = false,
                            MessagePlain = "Phasellus id odio volutpat, condimentum nisi vitae, dapibus mauris. Ut sed mi orci. Maecenas mi nunc, blandit nec hendrerit ac, maximus quis turpis. Nulla ex mi, consequat non orci posuere, tincidunt convallis nibh. Phasellus purus purus, porta quis lobortis at, lobortis sit amet lacus. Fusce sem libero, ullamcorper ut cursus quis, cursus id neque. Integer porttitor libero sit amet pellentesque porttitor. Nunc lacus enim, dapibus in scelerisque in, accumsan id felis. Donec posuere, dolor a tincidunt maximus, justo nisl imperdiet massa, vitae pharetra nunc erat non leo.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 26,
                            IsEdited = false,
                            MessagePlain = "Vestibulum ullamcorper porttitor eleifend. Etiam vehicula justo in est facilisis, nec lobortis dolor egestas. Proin lectus sapien, lacinia semper leo ac, imperdiet vehicula enim. Morbi sodales placerat ipsum et efficitur. Praesent ligula mi, ornare vel sagittis non, posuere non dui. Nunc interdum placerat mauris, ut elementum mauris aliquam in. Nulla egestas, tellus vel iaculis ullamcorper, nunc justo aliquam quam, et cursus felis mi non nulla. Sed ac auctor risus, ut aliquam turpis. Pellentesque vel tristique est, maximus iaculis sem. Phasellus turpis felis, euismod a elementum non, tincidunt id mauris. Praesent mattis tempor dui, et rutrum justo bibendum vel.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 27,
                            IsEdited = false,
                            MessagePlain = "Nunc et turpis et enim mollis volutpat consectetur eget mi. Cras ante erat, vehicula ac arcu quis, iaculis euismod est. Donec fringilla, urna sodales sodales vehicula, ligula mi finibus urna, nec euismod risus quam vel ex. Vestibulum auctor lorem consectetur nisl faucibus facilisis. In maximus sollicitudin justo id hendrerit. Integer sodales mollis quam, id ultricies tellus. Aliquam a purus nulla.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 28,
                            IsEdited = false,
                            MessagePlain = "Quisque porta sapien et augue semper, non sollicitudin mauris lacinia. Nunc rutrum nunc bibendum dolor posuere scelerisque. Nam consectetur lectus id rutrum aliquam. Aenean id tincidunt arcu. Aliquam ut pretium odio. Proin fringilla a nisl sed ultrices. Proin mauris est, pellentesque eget sodales id, cursus sed sapien. Phasellus tempor pretium erat, sit amet porta est viverra nec.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 29,
                            IsEdited = false,
                            MessagePlain = "Phasellus id odio volutpat, condimentum nisi vitae, dapibus mauris. Ut sed mi orci. Maecenas mi nunc, blandit nec hendrerit ac, maximus quis turpis. Nulla ex mi, consequat non orci posuere, tincidunt convallis nibh. Phasellus purus purus, porta quis lobortis at, lobortis sit amet lacus. Fusce sem libero, ullamcorper ut cursus quis, cursus id neque. Integer porttitor libero sit amet pellentesque porttitor. Nunc lacus enim, dapibus in scelerisque in, accumsan id felis. Donec posuere, dolor a tincidunt maximus, justo nisl imperdiet massa, vitae pharetra nunc erat non leo.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        },
                        new
                        {
                            Id = 30,
                            IsEdited = false,
                            MessagePlain = "Maecenas quis accumsan diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam gravida, lorem eget consectetur vulputate, libero odio pretium diam, ut suscipit mauris urna in lacus. Aliquam at aliquet nibh. Vivamus dapibus metus enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec in odio vitae augue tempor semper. Phasellus cursus mi vel quam dapibus, in semper est mollis. Nunc id bibendum dui, gravida scelerisque eros. Aliquam ac posuere arcu. Aliquam a vestibulum felis, sed ornare lectus. Morbi turpis eros, sagittis ut ligula ut, suscipit dictum neque. Nunc in tortor placerat, hendrerit odio ac, lacinia elit.",
                            SenderId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            Timestamp = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TopicId = 1
                        });
                });

            modelBuilder.Entity("ChatrBox.Data.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CommunityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastPost")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostPermission")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommunityId = 1,
                            Description = "System generated topic used for layout testing",
                            DisplayOrder = 0,
                            LastPost = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Testing",
                            PostPermission = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2cff87de-1389-4ef1-99cb-8da994816a60",
                            ConcurrencyStamp = "c367ad35-a4e5-4e97-bf2d-51e212de81cf",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "a4b7313a-317e-498b-8002-f65430ee638e",
                            ConcurrencyStamp = "dbea61dc-6f71-4bb2-9ac7-1257ecdbef54",
                            Name = "superAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "ba374366-a3ae-42bd-8254-a452d1de860a",
                            ConcurrencyStamp = "dff1aab9-3afe-4e29-a368-b71689f8ff8f",
                            Name = "moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = "3fa0fda4-4a86-4eb2-b18e-e503a3ffa5b9",
                            ConcurrencyStamp = "affbeb71-fba0-45a3-bfed-5f2aba165c6d",
                            Name = "InternalSystem",
                            NormalizedName = "INTERNALSYSTEM"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1209cf85-72db-45f8-bd6c-c86f6dc346c4",
                            RoleId = "2cff87de-1389-4ef1-99cb-8da994816a60"
                        },
                        new
                        {
                            UserId = "1209cf85-72db-45f8-bd6c-c86f6dc346c4",
                            RoleId = "a4b7313a-317e-498b-8002-f65430ee638e"
                        },
                        new
                        {
                            UserId = "1209cf85-72db-45f8-bd6c-c86f6dc346c4",
                            RoleId = "ba374366-a3ae-42bd-8254-a452d1de860a"
                        },
                        new
                        {
                            UserId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            RoleId = "2cff87de-1389-4ef1-99cb-8da994816a60"
                        },
                        new
                        {
                            UserId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            RoleId = "a4b7313a-317e-498b-8002-f65430ee638e"
                        },
                        new
                        {
                            UserId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            RoleId = "ba374366-a3ae-42bd-8254-a452d1de860a"
                        },
                        new
                        {
                            UserId = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            RoleId = "3fa0fda4-4a86-4eb2-b18e-e503a3ffa5b9"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ChatrBox.Data.Chatr", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("ImageHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Chatr");

                    b.HasData(
                        new
                        {
                            Id = "1209cf85-72db-45f8-bd6c-c86f6dc346c4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "578e3c7a-0545-43e3-8f35-cc55e74e6441",
                            Email = "example@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEH/Jmvxt5H6Wu/pZDsnnqOArFy24B4r8hHhTQpyD7J6L+MEQNbhT1vab3724uYt0CQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "659990fa-2c72-49a9-a02e-c319b0f958f4",
                            TwoFactorEnabled = false,
                            UserName = "admin",
                            ImageHash = "",
                            ImageUrl = "",
                            LastActive = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "b0af2ed0-5f6c-48f3-9e4e-10bcaaa00ace",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f83dba94-c5d9-4f6b-9c28-da8ec10ff2ba",
                            Email = "",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "CHEDDAR_CHATR",
                            PasswordHash = "AQAAAAEAACcQAAAAEFz3cKigapCO+J4Xiy7fDIq+lpg2/MPphgPkwhKHqBrgS47xKXF9/QefUvvtAUg2tQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f283f4f9-ac26-4496-8445-d2ed00b66e8d",
                            TwoFactorEnabled = false,
                            UserName = "Cheddar_Chatr",
                            ImageHash = "",
                            ImageUrl = "",
                            LastActive = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ChatrBox.Data.Community", b =>
                {
                    b.HasOne("ChatrBox.Data.Chatr", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ChatrBox.Data.CommunityUser", b =>
                {
                    b.HasOne("ChatrBox.Data.Chatr", "Chatr")
                        .WithMany()
                        .HasForeignKey("ChatrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChatrBox.Data.Community", "Community")
                        .WithMany()
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chatr");

                    b.Navigation("Community");
                });

            modelBuilder.Entity("ChatrBox.Data.Message", b =>
                {
                    b.HasOne("ChatrBox.Data.Chatr", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId");

                    b.HasOne("ChatrBox.Data.Topic", "Topic")
                        .WithMany("Messages")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("ChatrBox.Data.Topic", b =>
                {
                    b.HasOne("ChatrBox.Data.Community", "Community")
                        .WithMany("Topics")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChatrBox.Data.Community", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("ChatrBox.Data.Topic", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("ChatrBox.Data.Chatr", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
